spring:
  application:
    name: spring-boot-blueprint
  profiles:
    default: dev

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 300000
    refresh-token-expiration: 604800000
    refresh-token-absolute-expiration: 2592000000

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  avatar:
    default-url: ${DEFAULT_AVATAR_URL:https://res.cloudinary.com/demo/image/upload/v1/samples/people/default-avatar.png}