spring:
  application:
    name: spring-boot-blueprint
  profiles:
    default: dev

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 300000
    refresh-token-expiration: 604800000
    refresh-token-absolute-expiration: 2592000000